## Import

In [2]:
import numpy as np

 ## 1. Create a 3x3 array that contains a diagonal of nines.

In [48]:
arr = np.identity(3)
arr[[0,1,2],[0,1,2]] = 9
arr

array([[9., 0., 0.],
       [0., 9., 0.],
       [0., 0., 9.]])

In [50]:
arr = np.zeros((3,3))
for i in range(3):
    arr[i,i] = 9
arr

array([[9., 0., 0.],
       [0., 9., 0.],
       [0., 0., 9.]])

In [52]:
a = np.zeros((3,3))
np.fill_diagonal(a,9)
a

array([[9., 0., 0.],
       [0., 9., 0.],
       [0., 0., 9.]])

In [54]:
a = np.eye(3)* 9
a

array([[9., 0., 0.],
       [0., 9., 0.],
       [0., 0., 9.]])

In [56]:
a= np.diag([9,9,9])
a

array([[9, 0, 0],
       [0, 9, 0],
       [0, 0, 9]])

## 2. Create a 4 x 4 ndarray that only contains consecutive even numbers from 2 to 32 (inclusive) and use Boolean indexing to pick out the values that are within 1/2 standard deviations of the mean.


In [59]:
a = np.arange(2,34,2)
a

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32])

In [35]:
a.reshape(4,4)

array([[ 2,  4,  6,  8],
       [10, 12, 14, 16],
       [18, 20, 22, 24],
       [26, 28, 30, 32]])

In [63]:
mean = np.mean(a)
mean

17.0

In [67]:
STD = np.std(a)
STD

9.219544457292887

In [77]:
A = a > (mean - 0.5 * STD)
B = a < (mean + 0.5 * STD)
A
B

array([False, False, False, False, False, False,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True])

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True, False, False, False, False, False, False])

In [95]:
#C = np.where(A & B)
#a[C]

In [93]:
a[A&B]

array([14, 16, 18, 20])

## 3. Create a 9x9 array that contains only zero of type int.


In [98]:
np.zeros((9,9), dtype = int)

array([[0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0]])

## 4. Ask the user for a number n. Then, use broadcasting to create a n x n ndarray that has its first column full of ones, its second column full of twos, its third column full of threes, etc…


In [130]:
n = int(input("Enter an integer number n:"))
a= np.arange(1, n + 1)
row = a[np.newaxis, :] 

Enter an integer number n: 3


In [132]:
col = np.ones((n,1))

In [134]:
arr = row * col
arr

array([[1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.]])

## 5- https://codeforces.com/contest/381/problem/A


In [145]:
n = int(input("Enter the number of cards n:"))
cards = np.array(input().split(), dtype=int)
Sere_Points = 0
Dima_Points = 0
turn = 0

Enter the number of cards n: 7
 1 2 3 4 5 6 7


In [147]:
while cards.size:
    if cards[0]> cards[-1]:
        taken = cards[0]
        cards = cards[1:]
    else:
        taken = cards[-1]
        cards = cards[:-1]

    if turn %2 == 0:
        Sere_Points += taken
    else:
        Dima_Points += taken
    turn +=1

print(Sere_Points, Dima_Points)
        
        

16 12


## 6- https://codeforces.com/contest/707/problem/A


In [176]:
x = input("Enter the size of the array n&m:").split()
if len(x) != 2:
    print("Please enter two integers separated by space.")
else:
    n = int(x[0])
    m = int(x[1])
    

Enter the size of the array n&m: 3 2


In [178]:
pixels = []
for _ in range(n):
    row = input("Enter ixels row by row:").split()
    pixels.append(row)
photo = np.array(pixels)
if np.isin(photo, ['C', 'M', 'Y']).any():
    print("#Color")
else:
    print("#Black&White")

Enter ixels row by row: W W
Enter ixels row by row: W W
Enter ixels row by row: B B


#Black&White
